spring.application.name=restaurent-service

# ===================================================================
# POSTGRESQL DATABASE CONNECTION SETTINGS
# ===================================================================
# Format: jdbc:postgresql://<host>:<port>/<database_name>
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurantdb
spring.datasource.username=user
spring.datasource.password=user123
spring.datasource.driver-class-name=org.postgresql.Driver
server.port = 9091
# ===================================================================
# JPA / HIBERNATE CONFIGURATIONS
# ===================================================================
# Tells Hibernate to automatically update the database schema based on your @Entity classes
spring.jpa.hibernate.ddl-auto=update

# Shows the generated SQL queries in your console (great for debugging)
spring.jpa.show-sql=true

# Formats the SQL in the console neatly so it's readable
spring.jpa.properties.hibernate.format_sql=true

# Explicitly defines the dialect for PostgreSQL 10 or newer versions
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect